---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - 'recipe[unbound::default]'
    attributes:
